export const WORLD_CONFIG = {
  chunkSizeX: 16,
  chunkSizeY: 128,
  chunkSizeZ: 16,
  loadRadius: 3,
  preloadRadius: 4,
  unloadRadiusBuffer: 2,
  maxInteractionDistance: 6,
  generationBudgetPerFrame: 1,
  meshBudgetPerFrame: 1,
  skyColor: '#9cc7f5',
} as const;

export const PLAYER_CONFIG = {
  walkSpeed: 4.45,
  sprintSpeed: 6.25,
  crouchSpeed: 1.72,
  jumpVelocity: 7.2,
  gravity: 24,
  colliderWidth: 0.6,
  colliderHeight: 1.8,
  eyeHeight: 1.62,
  crouchEyeHeight: 1.15,
  mouseSensitivity: 0.0025,
  sprintDoubleTapWindowMs: 260,
  jumpRepeatDelayMs: 86,
  landingJumpCooldownMs: 54,
  autoJumpGroundedDelayMs: 18,
  jumpBufferMs: 95,
  coyoteTimeMs: 80,
  groundFrictionTick: 0.56,
  airFrictionTick: 0.92,
  waterHorizontalDragTick: 0.78,
  verticalDragTick: 0.984,
  groundWalkAccelerationTick: 0.11,
  groundSprintAccelerationTick: 0.17,
  groundCrouchAccelerationTick: 0.05,
  airWalkAccelerationTick: 0.022,
  airSprintAccelerationTick: 0.03,
  waterMoveAccelerationTick: 0.041,
  airStrafePenalty: 0.55,
  airSprintSideControlPenalty: 0.9,
  groundSprintForwardStrafeScale: 0.62,
  airSprintForwardStrafeScale: 0.76,
  fallStrafeBaseControlSpeed: 2.35,
  airborneWalkSpeed: 5.1,
  airborneSprintSpeed: 6.55,
  waterSwimSpeed: 2.35,
  waterSprintMultiplier: 1.08,
  waterSinkSpeed: -1.15,
  waterCrouchSinkSpeed: -1.9,
  waterRiseSpeed: 2.55,
  waterSurfaceTriggerHeightOffset: 1.62,
  waterSurfaceExitSinkSpeed: -0.75,
  waterSurfaceBandSinkSpeed: -0.45,
  waterSurfaceApproachRiseSpeed: 1.05,
  waterSurfaceBounceRiseSpeedStart: 1.25,
  waterSurfaceBounceRiseSpeedEnd: 0.24,
  waterSurfaceBounceSinkSpeedStart: -0.38,
  waterSurfaceBounceSinkSpeedEnd: -1.35,
  waterSurfaceBounceRiseMs: 220,
  waterSurfaceBounceSinkMs: 360,
  waterSurfaceApexDelayMs: 110,
  waterSurfaceBounceCooldownMs: 140,
  sprintJumpBoost: 0.28,
  landingApproachMinFallSpeed: 4.2,
  landingProbeSeconds: 0.09,
  landingApproachDamping: 0.74,
  maxHorizontalSpeed: 7.25,
  maxFallSpeed: 22,
  mcTickSeconds: 0.05,
} as const;

export const SAVE_CONFIG = {
  schemaVersion: 5 as const,
  databaseVersion: 3 as const,
  legacyWorldId: 'default-world' as const,
  appMetaKey: 'app-meta' as const,
  playerSaveIntervalMs: 2000,
  worldSaveDebounceMs: 500,
} as const;
